### ISSUE TITLE
JWT authentication error [Generate a JWT token (after being authenticated)]

### ISSUE THREAD

**Issue by 0x003e** [pac4j/undertow-pac4j-demo#9]
Hi,

![](http://i.imgur.com/9IhkVD6.png)

**Logs traces:**

```sh
UNDERTOW PAC4J DEMO 23:27:48.198 [XNIO-1 task-11] DEBUG o.p.core.engine.DefaultSecurityLogic - === SECURITY ===
UNDERTOW PAC4J DEMO 23:27:48.198 [XNIO-1 task-11] DEBUG o.p.core.engine.DefaultSecurityLogic - url: http://localhost:8080/jwt.html
UNDERTOW PAC4J DEMO 23:27:48.198 [XNIO-1 task-11] DEBUG o.p.core.engine.DefaultSecurityLogic - matchers: null
UNDERTOW PAC4J DEMO 23:27:48.198 [XNIO-1 task-11] DEBUG o.p.core.engine.DefaultSecurityLogic - clients: AnonymousClient
UNDERTOW PAC4J DEMO 23:27:48.198 [XNIO-1 task-11] DEBUG o.p.core.engine.DefaultSecurityLogic - currentClients: [#AnonymousClient# | name: AnonymousClient |]
UNDERTOW PAC4J DEMO 23:27:48.198 [XNIO-1 task-11] DEBUG o.p.core.engine.DefaultSecurityLogic - loadProfilesFromSession: true
UNDERTOW PAC4J DEMO 23:27:48.198 [XNIO-1 task-11] DEBUG o.p.core.engine.DefaultSecurityLogic - profiles: [#CommonProfile# | id: m | attributes: {username=m} | roles: [] | permissions: [] | isRemembered: false |]
UNDERTOW PAC4J DEMO 23:27:48.198 [XNIO-1 task-11] DEBUG o.p.core.engine.DefaultSecurityLogic - authorizers: null
UNDERTOW PAC4J DEMO 23:27:48.198 [XNIO-1 task-11] DEBUG o.p.core.engine.DefaultSecurityLogic - authenticated and authorized -> grant access
UNDERTOW PAC4J DEMO 23:27:48.198 [XNIO-1 task-11] WARN  org.pac4j.jwt.profile.JwtGenerator - Using the same key for signature and encryption may lead to security vulnerabilities. Consider using different keys
UNDERTOW PAC4J DEMO 23:27:48.199 [XNIO-1 task-11] ERROR io.undertow.request - UT005071: Undertow request failed HttpServerExchange{ GET /jwt.html request {Accept=[text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8], Accept-Language=[fr,fr-FR;q=0.8,en-US;q=0.5,en;q=0.3], Cache-Control=[max-age=0], Accept-Encoding=[gzip, deflate], DNT=[1], User-Agent=[Mozilla/5.0 (X11; Linux x86_64; rv:51.0) Gecko/20100101 Firefox/51.0], Connection=[keep-alive], Authorization=[Basic bTpt], Cookie=[JSESSIONID=uo3AFJyERD_-I1hMnjJ0_PNdUXIR4vvFb0ykQQwH], Referer=[http://localhost:8080/], Upgrade-Insecure-Requests=[1], Host=[localhost:8080]} response {}}
org.pac4j.core.exception.TechnicalException: com.nimbusds.jose.JOSEException: Couldn't create AES/GCM/NoPadding cipher: Illegal key size
        at org.pac4j.jwt.config.encryption.AbstractEncryptionConfiguration.encrypt(AbstractEncryptionConfiguration.java:38) ~[pac4j-jwt-1.9.4.jar:na]
        at org.pac4j.jwt.profile.JwtGenerator.internalGenerate(JwtGenerator.java:122) ~[pac4j-jwt-1.9.4.jar:na]
        at org.pac4j.jwt.profile.JwtGenerator.generate(JwtGenerator.java:102) ~[pac4j-jwt-1.9.4.jar:na]
        at org.pac4j.demo.undertow.DemoHandlers.lambda$jwtHandler$5(DemoHandlers.java:156) ~[classes/:na]
        at org.pac4j.undertow.handler.SecurityHandler.lambda$handleRequest$0(SecurityHandler.java:89) ~[undertow-pac4j-1.2.2.jar:na]
        at org.pac4j.core.engine.DefaultSecurityLogic.perform(DefaultSecurityLogic.java:139) ~[pac4j-core-1.9.4.jar:na]
        at org.pac4j.undertow.handler.SecurityHandler.handleRequest(SecurityHandler.java:87) ~[undertow-pac4j-1.2.2.jar:na]
        at io.undertow.server.Connectors.executeRootHandler(Connectors.java:202) ~[undertow-core-1.3.23.Final.jar:1.3.23.Final]
        at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:802) ~[undertow-core-1.3.23.Final.jar:1.3.23.Final]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_101]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_101]
        at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_101]
Caused by: com.nimbusds.jose.JOSEException: Couldn't create AES/GCM/NoPadding cipher: Illegal key size
        at com.nimbusds.jose.crypto.AESGCM.encrypt(AESGCM.java:93) ~[nimbus-jose-jwt-4.26.jar:4.26]
        at com.nimbusds.jose.crypto.ContentCryptoProvider.encrypt(ContentCryptoProvider.java:169) ~[nimbus-jose-jwt-4.26.jar:4.26]
        at com.nimbusds.jose.crypto.DirectEncrypter.encrypt(DirectEncrypter.java:124) ~[nimbus-jose-jwt-4.26.jar:4.26]
        at com.nimbusds.jose.JWEObject.encrypt(JWEObject.java:353) ~[nimbus-jose-jwt-4.26.jar:4.26]
        at org.pac4j.jwt.config.encryption.AbstractEncryptionConfiguration.encrypt(AbstractEncryptionConfiguration.java:36) ~[pac4j-jwt-1.9.4.jar:na]
        ... 11 common frames omitted
Caused by: java.security.InvalidKeyException: Illegal key size
        at javax.crypto.Cipher.checkCryptoPerm(Cipher.java:1039) ~[na:1.8.0_71]
        at javax.crypto.Cipher.implInit(Cipher.java:805) ~[na:1.8.0_71]
        at javax.crypto.Cipher.chooseProvider(Cipher.java:864) ~[na:1.8.0_71]
        at javax.crypto.Cipher.init(Cipher.java:1396) ~[na:1.8.0_71]
        at javax.crypto.Cipher.init(Cipher.java:1327) ~[na:1.8.0_71]
        at com.nimbusds.jose.crypto.AESGCM.encrypt(AESGCM.java:89) ~[nimbus-jose-jwt-4.26.jar:4.26]
        ... 15 common frames omitted

```

**Comment by leleuj** [comment]
I just logged in into the form page (m/m) and it successfully generates the token. Did you change the key size (`DemoServer.JWT_SALT`)?
Or maybe you need the "Java Cryptography Extension (JCE) Unlimited Strength"...
